[package]
name = "rust-file-scan"
version = "0.1.0"
authors = ["Ted Spence <ted@spence.net>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite", "numeric"] }
dotenv = "0.9.0"