[package]
name = "rust-file-scan"
version = "0.1.0"
authors = ["Ted Spence <ted@spence.net>"]
edition = "2018"

[dependencies]
dotenv = "*"
filescandb = { path = "filescandb" }
rusqlite = { version = "*", features = ["bundled"] }
