[package]
name = "filescandb"
version = "0.1.0"
authors = ["Ted Spence <ted@spence.net>"]
edition = "2018"

[dependencies]
diesel = { version = "*", features = ["sqlite", "chrono"] }
dotenv = "*"
libsqlite3-sys = { version = "*", features = ["bundled"] }
